version: '3.8'

services:
  sentiment-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}