import random as _random
from typing import Tuple


THEMES = [
    {
        "name": "FreeLimit",
        "titles": [
            "5 recordings isn't enough",
            "Hit your free limit?",
            "Out of free recordings?",
            "Free recordings filled up?",
            "The free tier is full",
            "Need more than 5?",
            "Stuck on the free plan?",
            "Free not enough anymore?",
            "Reached your recording cap?",
            "The free limit feels small",
        ],
        "bodies": [
            "Upgrade to Pro and record every call without any limit",
            "Pro gives you unlimited call recordings — forever",
            "Tap upgrade to remove the recording cap",
            "CallRecorder Pro has no recording limit — ever",
            "Switch to Pro and never hit a cap again",
            "Free is for trying. Pro is for real use",
            "Pro removes every limit — start now",
            "No caps, no limits — that's CallRecorder Pro",
            "Unlock unlimited call recordings in one tap",
            "Pro means recording every call, as much as you want",
        ],
    },
    {
        "name": "AiTranscription",
        "titles": [
            "Turn your calls into text instantly",
            "AI transcripts of every call",
            "Let AI handle your call notes",
            "Smart call transcription with one tap",
            "Call to text in seconds",
            "Stop typing — start recording calls",
            "Your calls, transcribed perfectly",
            "Get AI summaries of every call",
            "AI-powered call notes await",
            "Speak it. We write it",
        ],
        "bodies": [
            "Pro turns any call recording into accurate text in seconds",
            "Get full transcripts and AI summaries of every call with Pro",
            "Save hours each week — Pro transcribes your calls for you",
            "Pro reads your call recordings and writes the notes",
            "Smart AI summaries highlight what really matters in every call",
            "Pro turns long calls into short, clear summaries",
            "Transcribe business calls, interviews, and meetings automatically",
            "Search any spoken word inside your call recordings with Pro",
            "Pro's AI saves you from typing call notes ever again",
            "Get text, transcripts, and summaries — all from your calls",
        ],
    },
    {
        "name": "UseCases",
        "titles": [
            "Important call coming up?",
            "Recording a business call?",
            "Interviewing someone over the phone?",
            "Working on a sales call?",
            "Need proof of what was said?",
            "Recording a client call?",
            "Long conference calls ahead?",
            "Capturing a job interview?",
            "Driving and taking calls?",
            "Need your call on record?",
        ],
        "bodies": [
            "Pro records and summarizes every important call for you",
            "Pro turns every business call into searchable notes",
            "Get full interview transcripts in seconds with Pro",
            "Pro is the companion every sales rep needs on calls",
            "Capture exactly what was agreed — Pro has it on record",
            "Pro turns hours of client calls into clean, readable text",
            "Long conference calls become short summaries with Pro",
            "Conference calls — captured, transcribed, summarized",
            "Record calls hands-free on the road, read them later",
            "Pro keeps every call on record, forever",
        ],
    },
    {
        "name": "DontLoseDetails",
        "titles": [
            "Don't lose another important call",
            "Don't let key details slip away",
            "Your next big deal needs a recording",
            "Capture everything — forget nothing",
            "Call recordings pile up — keep them all",
            "Never miss a detail from a call again",
            "Save every important conversation",
            "Don't trust your memory alone",
            "Every call recording matters",
            "Don't let call details escape",
        ],
        "bodies": [
            "Pro lets you record every call, anytime — no limits",
            "Capture every conversation before details disappear with Pro",
            "Pro saves every call recording — your calls live forever",
            "Free up your brain. Let Pro remember every call for you",
            "Pro is the second brain your business calls deserve",
            "Important calls don't wait — Pro is ready when they happen",
            "Pro keeps every call recording safe and searchable",
            "The best calls happen unexpectedly — Pro captures them all",
            "Don't let another important call go unrecorded",
            "Pro means every call is recorded and remembered forever",
        ],
    },
    {
        "name": "UpgradeCta",
        "titles": [
            "Try CallRecorder Pro now",
            "Upgrade in one tap",
            "Get Pro today",
            "Tap to go unlimited",
            "Activate CallRecorder Pro",
            "Begin your Pro journey",
            "Start recording calls like a pro",
            "Make the switch today",
            "Step up to Pro",
            "Pro is one tap away",
        ],
        "bodies": [
            "Open the app and tap upgrade to start your Pro experience",
            "One tap and you're recording every call without any limit",
            "Tap to upgrade and unlock everything Pro offers",
            "Get Pro now and start recording every call today",
            "Activate Pro in seconds — record unlimited calls in seconds more",
            "Tap below to switch to Pro right now",
            "Open the app and tap upgrade — that's all it takes",
            "One tap unlocks unlimited call recordings and AI features",
            "Tap upgrade to get Pro features instantly",
            "Open the app now and start your Pro journey",
        ],
    },
    {
        "name": "SocialProof",
        "titles": [
            "Loved by thousands of users",
            "Top-rated call recorder",
            "The recorder pros choose",
            "Trusted by professionals worldwide",
            "Used daily by power users",
            "Why everyone's switching to Pro",
            "The favorite of serious callers",
            "Pros pick CallRecorder Pro",
            "Built for people who record calls",
            "Used by people who get things done",
        ],
        "bodies": [
            "Join thousands using Pro every day to record more calls",
            "Pro is the call recorder creators, lawyers, and sales reps rely on",
            "Discover why so many users upgrade to CallRecorder Pro",
            "Trusted by professionals worldwide — see why Pro is different",
            "See why power users stay with CallRecorder Pro",
            "Once people try Pro, they don't go back",
            "Loved by professionals who record calls daily",
            "The call recorder serious users actually use",
            "Pro is the choice of people who get things done on calls",
            "Find out why everyone's switching to CallRecorder Pro",
        ],
    },
    {
        "name": "WarmEmotional",
        "titles": [
            "Hey, we miss you",
            "Come back to CallRecorder",
            "Your calls deserve better",
            "We saved your spot",
            "Your recordings need you",
            "Make CallRecorder truly yours",
            "CallRecorder is better with you",
            "You deserve unlimited",
            "Pro fits your style",
            "Built for someone like you",
        ],
        "bodies": [
            "We made Pro for users like you — come give it a try",
            "Your calls are unique. Pro gives them the storage they deserve",
            "We saved your spot in CallRecorder Pro — come back anytime",
            "Your recordings have been waiting — let's go unlimited",
            "CallRecorder Pro feels different — like it was made for you",
            "Make CallRecorder truly yours with Pro",
            "Pro is built for people who care about their calls",
            "You deserve unlimited recordings, transcripts, and more",
            "Pro fits how you record calls — try it and feel the difference",
            "Designed for users like you — try CallRecorder Pro today",
        ],
    },
    {
        "name": "Curiosity",
        "titles": [
            "Ever wonder what Pro unlocks?",
            "Curious about CallRecorder Pro?",
            "Want to see what Pro does?",
            "Wondering why people upgrade?",
            "Ready for what's inside Pro?",
            "Imagine never running out of recordings",
            "What if every call was recorded?",
            "Curious what unlimited feels like?",
            "Want to know the Pro difference?",
            "Ready for a smarter call recorder?",
        ],
        "bodies": [
            "Pro unlocks unlimited call recordings, AI transcripts, and more",
            "CallRecorder Pro is what your recorder was always meant to be",
            "See for yourself — Pro changes how you handle every call",
            "People upgrade because Pro removes every limit",
            "Try Pro and see why so many users never go back",
            "Imagine recording every meeting, client call, and interview — done",
            "No limits, no caps, just recording — that's CallRecorder Pro",
            "Unlimited means you'll forget free even existed",
            "Pro is faster, smarter, and built for daily call recording",
            "Try the smarter way to record — CallRecorder Pro",
        ],
    },
    {
        "name": "Productivity",
        "titles": [
            "Save hours every week",
            "Stop typing call notes",
            "Your calls are faster than your fingers",
            "Call recording, made effortless",
            "Time-saving call recordings",
            "Capture more calls, type less",
            "Less typing, more doing",
            "Productivity, supercharged",
            "Get more done with Pro",
            "Work smarter, record faster",
        ],
        "bodies": [
            "Pro saves you hours every week with AI call transcription",
            "Stop typing call notes — Pro turns every call into text",
            "Record your calls. Pro writes the notes faster than you can",
            "Pro makes call recording effortless and notes automatic",
            "Get back hours every week — Pro handles the typing",
            "Capture more calls, type less — Pro does the work for you",
            "Less typing means more time to focus on what matters",
            "Pro is the productivity boost your workflow needs",
            "Pro helps you get more done in less time, every day",
            "Work smarter with unlimited call recordings and instant text",
        ],
    },
    {
        "name": "Value",
        "titles": [
            "Less than a coffee a day",
            "Pro is worth every cent",
            "Big value, simple pricing",
            "Affordable. Powerful. Yours",
            "Pro: simple price, big features",
            "Made for everyone",
            "Pricing that just makes sense",
            "Pro fits any budget",
            "Pay less, get more",
            "The best value in call recording",
        ],
        "bodies": [
            "CallRecorder Pro costs less than a coffee per day — and does much more",
            "Pro is worth every cent for unlimited recordings and AI transcription",
            "Big value, simple pricing — that's CallRecorder Pro",
            "Powerful call recording features at a price that fits any budget",
            "Pro packs unlimited recordings and AI into one simple plan",
            "Affordable Pro pricing built to fit everyone",
            "Pricing that makes sense — features that change everything",
            "A small daily price for unlimited call recordings forever",
            "Pay once a month, record every call all month long",
            "The best value in call recording — CallRecorder Pro",
        ],
    },
]


def pick_random_coherent(rng: _random.Random | None = None) -> Tuple[str, str]:
    """Return a (title, body) pair from the same randomly chosen theme."""
    r = rng or _random.Random()
    theme = r.choice(THEMES)
    title = r.choice(theme["titles"])
    body = r.choice(theme["bodies"])
    return title, body