"""add_name_to_user

Revision ID: 3593b0e93e82
Revises: f7a8b9c0d1e2
Create Date: 2026-04-22 13:45:11.392861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3593b0e93e82'
down_revision = 'f7a8b9c0d1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('fcm_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fcm_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
